[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edstem"
version = "0.1.0"
dependencies = [
    "edapi>=0.1.0",
    "mcp>=1.0.0",
    "requests>=2.32.0",
    "python-dotenv>=1.0.0",
]

[project.scripts]
edstem = "edstem.main:main"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["edstem"]
