name: MCP Servers CI

on:
  pull_request:

jobs:
  check_mcp_servers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_MCPPRO }}

      - name: Pull docker image
        run: |
          docker pull ghcr.io/sudobase-ai/sudomcp/mcppro:master

      - name: Verify MCP servers
        run: |
          docker run --rm \
            -e LOG_LEVEL=DEBUG \
            --name mcppro-server \
            --entrypoint mcppro \
            --volume ${{ github.workspace }}:/app/mcp-servers-repo \
            ghcr.io/sudobase-ai/sudomcp/mcppro:master -- dev verify-servers --tools
